src/utils/axios.ts

- axios 를 추상화 하는 인터페이스인 axiosInstance를 생성하여 사용 합니다
- axios interceptor 를 활용하여 request, response 를 보낼 수 있다
```jsx
// request 요청 설정 중 withCredentials 옵션을 추가해서 보내줌
axiosInstance.interceptors.request.use(function setConfig(config) {
config.withCredentials = true;
return config;
});
```
```tsx
// 기존 코드
axios.get('/api/text').then().catch();
// 변경 코드
axiosInstance.get('/api/text').then().catch();
```
- 현재 백엔드 api가 없기 때문에 mock데이터를 만들어서 사용할 예정 따라서 base url 도 추가하지 않음
- 이후 백엔드 api가 생성되면 코드 추가 예정
- #11

[Feat] axiosInstance 생성

---

.github/pull_request_template.md

자주 까먹는 것 같아 npm run build항목을 체크리스트에 추가하면서 소소하게 여러가지 바꿔봤습니다.
읽어보시고 수정하고 싶으신 부분이 있다면 comment해주세요!
1. 풀리퀘스트 템플릿 변경
- issue-> pull-requset로 이름 변경
- check box-> 숫자로 변경
- 체크리스트에 npm run build 항목추가
- screen capture항목 추가

[Chore] : pull-request template 변경

---

src/app/create/page.tsx
src/app/login/page.tsx
src/app/page.tsx

- 태그 내부에 // 텍스트 작성 시 주석처리되서 에러 발생으로 인해 {₩//₩}으로 변경
- React component 함수 이름 첫자 소문자로 작성 시 에러 발생으로 인해 대문자로 변경
- #28

bug/build시 에러 발생 해결#28

---

src/component/BottomButton.tsx

props는 총 4개입니다.
1.   name: string 
버튼에 표시할 버튼의  이름입니다.
2.  width: string 
버튼의 길이입니다. className에 직접적으로 입력되므로, width가 아닌 basis style도 표시가능합니다.
3.  onClickHandler: () => void 
버튼이 클릭되었을 때 실행할 핸들러입니다. 화살표함수 형태로 입력해주시면 됩니다.
4. disabled: boolean
현재 버튼이 활성화 상태인지 아닌지를 알리는 boolean값입니다.
아래와 같이, import 후 return 문 안에서 ```<button/>```대신 ```<BottomButton/>```을 넣어주세요.
```javascript
import BottomButton from '@/component/BottomButton';
export default function example(){
return(
<BottomButton
name="취소"
width="basis-1/5"
onClickHandler={handleClick}
disabled={false}
/>
);
}
```
- 왼쪽의 취소버튼이 활성화 상태, 오른쪽의 완료 버튼은 비활성화 상태입니다. 
- 각각 disabled의 값을 false, true로 받고 있습니다.
- #35

feat: BottomButton 생성

---

tailwind.config.js

- 픽스된 디자인 컬러코드 tailwind 적용
- #72

feat: strcat 테마별 색상 tailwind 적용#72

---

src/component/export/Writer.tsx

- 긴급 Pr
- npm run build 에러 부분 수정
- props 에서 사용하는 타입을 잘 못 수정하여 build error 가 나는 코드 수정
-

[Fix]npm run build error 수정

---

src/app/create/page.tsx
src/app/group/[id]/page.tsx
src/app/personal/[id]/page.tsx
src/component/ObserveContent.tsx
src/component/StrcatBoard.tsx
src/component/ThemeChange.tsx
src/recoil/theme.ts

- 전역 테마를 설정할 theme recoil 변수 값 설정
- 이미 사용하고 있던 전역 변수 이름 변경 및 맵핑
- #77

style: 전역 recoil 스타일 적용 #77

---

src/app/login/check/page.tsx
src/app/login/page.tsx
src/component/StrcatHeader.tsx
src/hooks/useInterceptor.tsx
src/hooks/useLogin.ts
src/recoil/login.ts

- 로그인 체커 구현
- 로그인 로직 구현 시 백앤드에서 프론트의 /login/check?token=... 방식으로 리다이렉트 함
- 이에 대응하는 페이지를 만들어 로컬 스토리지로 저장하는 로직 구현
- Axios config baseUrl 값 추가
- Axios config token 값 추가
- login state recoil로 변경
- 현재 strcatHeader가 레이아웃이 아닌 각 페이지 상위에서 호출하고 있어 전역 변수로 분리 하였습니다
- axios ingterceptor 에 있는 함수 중 any type props 함수 -> 정확한 타입으로 변경
- #79

feat/login checker#79

---

src/component/Drawer.tsx
src/component/Modal/index.tsx
src/utils/handleBackground.tsx

- Hot FIX
- 드로어에서 로그인 토큰이 없을 경우 api를 호출하지 않도록 변경했습니다.
- 이전 풀리퀘에서 말했던 handle Background를 util함수로 분리 후 modal과 drawer에 적용했습니다.
- #86 
- #65

[HOT FIX] : drawer에서 호출하는 api로 인해 login으로 가는 버그 해결

---

src/app/create/group/page.tsx

- 도경님이 제작하신 create페이지를 참고해서,
- create/group route를 갖는 그룹 생성 페이지를 만들었습니다
- 피그마의 디자인에 따라 원래 create페이지와 다르게 문구와, text size를 수정했습니다. 
- textarea가 title 양에 따라서 줄어들고, 늘어날 수 있도록 on change handler로 resize를 해주는 함수를 넣었습니다.
- title 입력시 엔터에 대해서 동작하지 않도록 막았습니다. 
- 입력완료시, 그리고 에러시에 동작하는 모달을 띄웠습니다.
모바일뷰 스크린, 웹뷰 스크린
- #92

[Feat] group create 페이지 구현 #92

---

src/app/login/page.tsx

1.  flex를 적용하여 로그인 페이지 css 수정
2. 테마 recoil을 불러와 적용하여 배경색 글씨색 수정 
- #95

feat/로그인 페이지 디자인 적용#95

---

src/app/create/page.tsx

1. useSearchparams를 이용한 groupId를 얻고 해당 정보를 get으로 요청하였습니다.
- #106

(kan 59)feat/create page setlink#93

---

src/app/group/[id]/summary/page.tsx
src/app/personal/[id]/summary/page.tsx

1. backbutton에 onclick 시 router.push(주소)를 추가하였습니다.
- #113

feat/summary페이지 backbutton 구현#113

---

src/app/api/personal/data.json
src/app/personal/[id]/page.tsx
src/utils/handleShare.ts

- 공유하기 기능을 구현했습니다.
- 안드로이드 및 pc웹의 경우 클립보드에 복사가 되고, IOS는 브라우저의 공유하기 bottom이 뜹니다.
- 현재 https://strcat.me 도메인이 적용되어있어서 추가할 params를 위와같이 적용해주면 됩니다. 
- #112

[feat] 공유하기 기능 #112

---

src/app/page.tsx

- 글씨 위치를 relative 속성의 top을 이용하여 위치 수정
- #117

[Feat] 메인 페이지 로그인 버튼 텍스트 정렬#117

---

src/app/group/[id]/summary/page.tsx
src/app/personal/[id]/summary/page.tsx

- 솔님이 만드신 handleshare 함수 공유하기 버튼에 적용하였습니다.
- #125

feat/summary페이지 share 기능 추가#125

---

src/app/page.tsx

- ios에서 주석이 표시되지 않는 오류를 수정하였습니다.
- #133

[fix]ios 주석 표시#133

---

src/component/Drawer.tsx
src/component/StrcatHeader.tsx

- drawer의 로그아웃 기능을 추가했습니다.
- drawer에서 group board list 가 없을 경우 drop button이 보이지 않도록 수정했습니다.
- header에서 로그인 / 홈으로 버튼을 구분하는 조건문의 pathname 을 login->/login으로 수정했습니다
- #121

[Feat] drawer 로그아웃 기능추가

---

src/app/group/[id]/page.tsx
src/app/personal/[id]/page.tsx
src/component/Icon/Share.tsx
src/component/Modal/Photo.tsx
src/component/Modal/index.tsx
src/component/ObserveContent.tsx
src/component/ObserveTitle.tsx
src/component/ShareButton.tsx
src/component/StrcatBoard.tsx

- 통합테스트에서 나온 에러를 1차 수정하였습니다.
- 글작성하기 disabled되는 부분 수정
- 컨텐츠 있을경우 공유하기 버튼 없애기
- break-all 추가 (영어 계속 입력될경우 break)
- 공유하기 디자인 적용, 그룹페이지 공유하기 적용
- 공유하기 에러 수정
- #144

[Fix] 조회페이지 통합테스트 1차 수정  #144

---

src/app/create/group/page.tsx
src/app/create/page.tsx
src/app/globals.css
src/app/group/[id]/page.tsx
src/app/login/check/page.tsx
src/app/page.tsx
src/app/personal/[id]/page.tsx
src/app/personal/[id]/summary/page.tsx
src/component/Drawer.tsx

- drop button이 디자인과 다르게 반대로 되어있어 수정했습니다.
- logout 시 header로그인 버튼이 새로고침되어야만 보이는 버그가 있어 새로고침없이도 로그인 버튼이 보이도록 수정했습니다 .
- login 페이지에서 홈으로 버튼 클릭시 main으로 이동하지 않는 버그가 있어 수정했습니다. 
- svg icon을 디자인에 맞춰 변경했습니다. ( long cat, shortdut)
- 특수문자가 입력되지 않는 버그가 있어 수정했습니다.  특수문자를 입력을 위해 dot gothic16 font에 설정되어있던 unicode를 삭제하고, 한글폰트가 깨지는 것을 막기위해, space, enter unicode만 한글 폰트에 추가했습니다. 
- drawer background에  grayscale을 적용했습니다. 
- 그룹 스트링캣 생성을 메인에서 눌렀을 때 redirect url이 create로 되어있어 create/group으로 수정했습니다. 
- create스트링캣 이동전에 login이 되어있는지 확인하고, group 스트링캣에서 글 작성자가 새로운 스트링캣을 생성하려고 할때, personal스트링캣에서도 동일한 상황에서 login을 확인후 login이 되어있지 않으면 로그인 페이지로 이동하도록 변경했습니다.
- localstorage에 loginsuccess url에 대해서 설정을 하고, 지워주는 부분이 없어서 추가했습니다.
- #144

[Hot Fix!] : Combine Test 1차수정

---

src/app/modal/page.tsx

[fix]빌드에러해결

---

src/app/create/group/page.tsx
src/app/create/page.tsx
src/app/group/[id]/export/page.tsx
src/app/group/[id]/page.tsx
src/app/login/check/page.tsx
src/app/login/page.tsx
src/app/not-found.tsx
src/app/page.tsx
src/app/personal/[id]/export/page.tsx
src/app/personal/[id]/page.tsx
src/component/Add.tsx
src/component/Drawer.tsx
src/component/PhotoUpload.tsx
src/recoil/theme.ts
tailwind.config.js

- not found 버튼이 눌리지 않는 버그 해결
- drawer api요청이 안가는 버그 해결
- add컴포넌트 20자 이내일 경우 디자인 수정
- placeholder디자인 수정
- 제한 글자수 error 디자인 수정
- export page 바텀 버튼 디자인 수정
- logout 상태에서 create 페이지 이동시 이전 페이지로 돌아가도록 변경 (login_success_url을 삭제하지 않음)
- 경우의 수 
1. main-> create 
2. main->create/group 
3. personal->create
4. group->create
- add컴포넌트, notfound페이지의 버튼을 select-none처리
- #144

[HOT FIX] : 2차 통합 테스트에서 발견한 버그 해결 및 수정 사항 반영

---

src/app/create/group/page.tsx
src/app/create/page.tsx
src/app/login/page.tsx
src/app/page.tsx
src/component/BottomButton.tsx
src/component/ThemeChange.tsx

1. 글자 수 색깔 테마 지정
2. create 페이지 router.push -> router.back으로 변경
3. 버튼 내부의 텍스트 셀렉트 금지 설정
- #163

[fix]3rd test hotfix#163

---

src/component/Add.tsx
src/component/PhotoUpload.tsx

- content가 20자 미만일 경우 보여주는 문구를 에러 색상으로 추가했습니다.
- content 글자 수 제한을 알려주는 인디케이터의 스타일을 조정했습니다.
- backend의 요청에 맞춰 pictures api에 전송하는 photo data의 content-type을 image/png, image/jpeg, image/jpg로 변경했습니다.
- writer width가 iphone se화면에서 깨져보여서, 수정했습니다.
- writer 가 width가 길어질 때 From/writer, 글자 수 제한이 각각 양쪽 margin선에 맞춰서 붙어야한다고 지수님께서 말씀하셔서 수정했습니다.
- iphone chrome에서 contet 를 눌렀을 때 캐럿이 보이지 않는 문제를 해결할 방법을 찾았지만, 로컬에서 테스트를 할 수 없어 배포를 위해 커밋했습니다.
https://github.com/RollingPaper42/Front-End/assets/46983641/80643088-a98f-43f4-9398-fdae25c2b071
- #168

[Fix] Add component 버그 해결 및 디자인 변경사항 반영

---

src/app/layout.tsx

overscroll none이라는 css를 body에 적용해서 하얀색 화면이 노출되는것을 막았습니다.
- #178

[feat]overscoll#178

---

src/app/personal/[id]/page.tsx

[Fix] window type error#163

---

src/app/create/group/page.tsx
src/app/create/page.tsx
src/app/group/[id]/export/page.tsx
src/app/personal/[id]/export/page.tsx

1. backheader 컴포넌트를 페이지에 적용시켰습니다.
2. Theme 관련된 부분은 merge때문에 바뀐거 같습니다.
- #163

[fix]backheader 컴포넌트 적용

---

src/app/globals.css

[HotFix] font 모음 unicode적용 #162

---

src/app/create/group/page.tsx
src/app/create/page.tsx
src/app/group/[id]/export/page.tsx
src/app/group/[id]/page.tsx
src/app/group/[id]/summary/page.tsx
src/app/login/page.tsx
src/app/not-found.tsx
src/app/page.tsx
src/app/personal/[id]/export/page.tsx
src/app/personal/[id]/page.tsx
src/app/personal/[id]/summary/page.tsx
src/component/Add.tsx
src/component/BottomButton.tsx
src/component/GroupMainTitle.tsx
src/component/HeaderLayout/BackButtonHeader.tsx
src/component/Modal/Confirm.tsx
src/component/Modal/Error.tsx
src/component/Modal/ExportSuccess.tsx
src/component/ObserveContent.tsx
src/component/ObserveTitle.tsx
src/component/PhotoUpload.tsx
src/component/ShareButton.tsx
src/component/StrcatGroupTitle.tsx
src/component/SummaryBoard.tsx
src/component/export/ExportBoard.tsx
src/recoil/font.ts
tailwind.config.js

tailwind.config.js에 폰트 사이즈 및 line height 및 letterspacing을 설정하였습니다.
tailwind.config.js에 설정한 커스텀을 가져와 recoil에 font.ts를 만들고 피그마에 정리된 폰트 typography에 맞게 정리하였습니다.
현재 text-[픽셀]으로 된 css는 font.ts에 맞게 다 수정하였습니다.
폰트 사이즈 커스텀 적용하는 법
작성하려는 폰트 사이즈 line height값을 확인한 후 해당 typography를 확인한 후 코드에 적용합니다.
ex) text-[18px] => ${bodyFont.category1}
- #186

[Refactor]font_theme 전역 적용#186

---

src/component/HeaderLayout/DrawerItem.tsx
src/component/HeaderLayout/DropListItem.tsx

- 드래그 불가능하도록 drop list 와 drawer item들에 select-none속성을 부여했습니다.
- #189

[Fix] drawer 드래그 불가능하게 변경 #189

---

src/app/create/group/page.tsx
src/app/create/page.tsx
src/app/group/[id]/export/page.tsx
src/app/group/[id]/page.tsx
src/app/group/[id]/summary/page.tsx
src/app/login/page.tsx
src/app/not-found.tsx
src/app/page.tsx
src/app/personal/[id]/export/page.tsx
src/app/personal/[id]/page.tsx
src/app/personal/[id]/summary/page.tsx
src/component/Add.tsx
src/component/GroupMainTitle.tsx
src/component/HeaderLayout/BackButtonHeader.tsx
src/component/HeaderLayout/DefaultHeader.tsx
src/component/HeaderLayout/Drawer.tsx
src/component/HeaderLayout/DropList.tsx
src/component/HeaderLayout/DropListItem.tsx
src/component/Loading.tsx
src/component/ObserveContent.tsx
src/component/ObserveTitle.tsx
src/component/PhotoUpload.tsx
src/component/ShareButton.tsx
src/component/StrcatGroupTitle.tsx
src/component/ThemeChange.tsx
src/component/export/ExportBoard.tsx
src/recoil/IconTheme.ts
src/recoil/bgTheme.ts
src/recoil/textTheme.ts
src/recoil/theme.ts

theme.ts안의 bg값들은 bgTheme text값들은 textTheme icon값들은 iconTheme의 파일들로 각각 분류하여 리팩토링을 하였습니다.
리팩토링 후 전체 파일에 리팩토링 내용을 적용하였습니다.
- #185

[Refactor]테마 리팩토링 및 전체 적용#185

---

src/app/layout.tsx
src/component/ThemeChange.tsx
src/utils/axios.ts

- layout페이지에서 Inapp 태그를 recoilstate 상단으로 올렸을 때 갤럭시에서 테스트를 해봤는데 문제 없었습니다.
- #202

[Refactor] recoilstate 상단으로 Inapp 태그 이동#202

---

src/app/InApp.tsx

- InApp  리팩토링과 주석을 추가했습니다.
- 안드로이드 폰에서 지속적으로 삼성 브라우저, 크롬중 어떤 브라우저를 사용할 건지 묻는 창이 뜨는 버그를 수정하기 위해 삼성 브라우저에 대해서는 inapp브라우저를 허용했습니다.
- #213

[Refactor] inApp refactoring #213

---

src/app/toast/page.tsx
src/component/Toast.tsx
tailwind.config.js

- 디자인 변경사항에 따라 토스트를 생성하였습니다.
- 사용법은 참고용 페이지인 toast/page를 참고하시면 됩니다.
https://github.com/RollingPaper42/Front-End/assets/114637463/2e00e4ff-b51d-41c1-8d1b-fb08b1a32b9b
- #207

[feat] toast 생성

---

src/app/create/page.tsx
src/app/toast/page.tsx
src/component/Toast.tsx
tailwind.config.js

- create페이지 리팩토링하였습니다
- confirm모달 호출시 async를 제거하였습니다
- camel케이스로 변경하였습니다
- 불필요한 import제거하였습니다
- title에서 버튼 disabled되는 부분이 한박자씩 밀리던 것을 수정하였습니다
https://github.com/RollingPaper42/Front-End/assets/114637463/cfd46320-fe98-4f02-a28a-129e2f346978
- #212

[refactor] create페이지 리팩토링

---

src/app/create/page.tsx
src/component/Textarea.tsx
tailwind.config.js

타이틀 및 글 작성 시 textarea 부분을 컴포넌트화 시켰습니다.
width,
maxLength,
placeholder,
textColor,
height,
onTextChange,
width는 width입니다. 
maxLength는 글자 최대 수입니다. 
placeholder은 placeholder시 문구입니다.
textColor은 입력 시 글자색입니다.
onTextChange는 textarea의 입력 값을 호출한 부분입니다.
ex)
onTextChange = {handleTitleChange}
const [title, setTitle] = useState();
const handleTitleChange = (newTitle: string) => {
setTitle(newTitle);
};
이렇게 쓴다면 textarea의 입력한 text를 title에 넣을 수 있습니다.
- #225

[Feat] textarea component#225

---

src/app/create/page.tsx
src/app/globals.css
src/app/personal/[id]/page.tsx
src/component/ObserveContent.tsx
src/recoil/theme/bgTheme.ts
src/recoil/theme/textTheme.ts
tailwind.config.js

- 변경된 디자인에 따른 personal 페이지 css 수정 및 테마 파일 수정
- 하이라이트 텍스트 background color 추가
- npm run build error 수정
- 테마가 확정되면 테마 파일 정리 작업필요
- #204

[style] 변경된 디자인에 따른 personal 페이지 css 수정 및 테마 파일 수정 #204

---

src/app/personal/[id]/page.tsx
src/hooks/useScroll.tsx

- Ios 사파리에서 스크롤 시 스크롤강도에 따라 헤더와 바텀 버튼이 보이는 문제를 수정했습니다. 
- 관련해서, 터치시에도 헤더의 가시성을 변경하도록 했습니다.
- #246

[Fix]  scroll event수정 #246

---

src/component/Modal/PhotoModal.tsx

- 포토모달 하이라이트 디자인을 수정하였습니다. 
- #220

[Fix] 포토모달 하이라이트 디자인 수정

---

src/component/HeaderLayout/Drawer.tsx
src/component/HeaderLayout/DropList.tsx
src/component/HeaderLayout/DropListItem.tsx
src/component/Icon/drawer/Check.tsx

-  drawer 클로즈 될때 overflow = 'auto' 옵션을 주어 스크롤 막았던 것을 풀었습니다.
- check svg이미지를 수정하였습니다.
- 아이폰 SE2에서도 깨지지 않도록 전체적으로 마진과 높이를 조정하였습니다.
- #223

[Fix] drawer 에러사항 수정

---

src/app/page.tsx
src/app/personal/[id]/page.tsx
src/component/ObserveContent.tsx
src/utils/focusToHighlight.ts

[Feat] highlight focus#245

---

package-lock.json
package.json

- import sort plugin설치 후 잘 작동되지 않는 문제가 있어, @latest로 다시 install했습니다.
- npm install, vscode reload후 사용부탁드립니다.
- build시 보여지는 이름도 strcat 1.0.0 으로 변경했습니다.
- #257

[Fix] prettier plugin 버전 변경 #257

---

src/app/personal/[id]/Summary.tsx
src/app/personal/[id]/page.tsx

- 빌드 에러 해결
- 디자인 변경사항 수정
- #262

Fix/build error design fix#262

---

tailwind.config.js

-  drawer 변경사항 머지하면서 발생했던 tailwind.config 에러를 수정하였습니다.
- conflict해결하고 머지하면서 변경사항을 두개를 동시에 받았는데, 코드가 겹치면서 생긴 에러였습니다.
- merge할때 정확히 확인하겠습니다. 🥲
- #223

[Fix] tailwind.config 에러 수정

---

src/app/personal/[id]/PhotoPreview.tsx
src/app/personal/[id]/page.tsx
src/component/ObserveContent.tsx

- 사진 position absolute로 변경에 따른 top 값 지정
- 이미지 크기 46px + 원래 있던 패딩 5px => 51px
- summary 글 absolute로 변경 top 에서부터 100px 위치로 고정
- highlight board 위치 위에서부터 40%로 고정 
- #265

Fix/content photo display#265

---

src/app/create/page.tsx
src/app/personal/[id]/add/Writer.tsx
src/app/personal/[id]/add/page.tsx
src/component/HeaderLayout/TitleHeader.tsx
src/component/Textarea.tsx

1. Add page
1. 모달 문구 수정, 모달 호출 방식 수정
2. title header close버튼 클릭시 모달 호출 추가
3. title header 디자인 변경사항 반영 (padding추가)
4. Writer component 분리
5. TextArea 호출 방식 수정
2. TextArea 내부 props변경
1. maxheight-> maxHeight로 수정
2. TextArea 내부 props height 삭제 -> h-auto로 고정
- #273

[Fix] add페이지 자잘한 수정 

---

src/recoil/newtheme/bgTheme.ts
src/recoil/newtheme/default.ts
src/recoil/newtheme/textTheme.ts
src/recoil/newtheme/theme.ts
tailwind.config.js

- theme 별로 recoil에 theme.ts를 만들어 정리하였습니다.
1. default 값들인 부분을 default.ts 파일에 정리하였습니다.
2. figma에 정리된 부분만 변경됩니다.
https://www.figma.com/file/g3HOlIBjDuzrFTARibhgdV/%EB%A1%A4%EB%A7%81%ED%8E%98%EC%9D%B4%ED%8D%BC!?type=design&node-id=3962-54680&mode=design&t=ZgdI4hjMxP4CrGP5-0
3. 기존의 theme 파일을 건들여 제가 수정하면 confilct가 많이 일어날꺼 같아서 newTheme라는 파일에 넣었습니다.
* 각자 적용하시고 저한테 말씀해주시면 제가 Theme 파일 삭제하겠습니다.
- #276

[Reafactor]테마 정리#276

---

src/app/page.tsx
src/component/HeaderLayout/BackButtonHeader.tsx

- theme머지과정에서 생긴 오류를 수정하였습니다
- 백버튼에 백그라운드 색상을 넣었습니다
-

[Fix] theme 머지과정에서 생겼던 오류 수정

---

src/app/page.tsx

-  메인페이지로 들어올시 테마를 기본테마로 변경되게 하였습니다
-

[Fix] 메인페이지 들어올 시 night테마로 변경

---

src/app/personal/[id]/page.tsx
src/component/BottomButton.tsx

- button에 props로  shadow인 경우 true를 전달해서 조회 페이지에서만 shadow가 들어간 버튼을 보도록했습니다.
- #311

[Fix] 조회 페이지에서 부르는 button만 shadow가 들어가도록 변경 #311

---

src/app/page.tsx
src/component/Modal/PhotoModal.tsx

- 디자이너 요청으로 close버튼의 간격을 조정하였습니다 
-

[Fix] photoModal close버튼 간격조정

---

src/component/Modal/Confirm.tsx
src/component/Modal/Error.tsx
src/component/Toast.tsx
tailwind.config.js

- text opacity가 들어가 있으면 안되는 cofirm modal, error modal, toast에서 opacity를 삭제하고 opcaity가 들어간 color로 text를 변경했습니다.

style : text opacity 제거

---

src/app/personal/[id]/page.tsx
src/component/HeaderLayout/TitleHeader.tsx

-  add 페이지 접속 시 헤더 띄우기 
- #328

fix: 잘 못 지운 코드 수정: add 페이지 접속 시 헤더 띄우기 #328

---

src/component/Modal/Error.tsx
src/component/Modal/PhotoModal.tsx
src/component/PhotoUpload.tsx

- 압축후에도 1mb이상일 경우 에러모달을 추가햇ㅆ습니다

hotfix : 압축실패시 에러모달창 추가

---

src/app/page.tsx
src/utils/theme/bgTheme.ts

[Style] cta color#342

---

next.config.js
src/app/layout.tsx
src/app/personal/[id]/PhotoPreview.tsx
src/component/Photo.tsx

- s3 link를 env에 추가하고, next config를 추가로 구성해서 next Image태그에서 s3 link를 받아서 보여줄 수 있게 했습니다.ㄷ
- 또한 layout에 들어있던 ga, naver seo, clarity와 같은 id값을 env로 이동했습니다.
- #58

[Fix] Image S3 link 추가

---

src/app/page.tsx

- 메인페이지 아래에 디바이스 크기에 따라 bottomPadding을 주었습니다
- #348

[Fix] main bottom padding#348

---

src/component/BottomImage.tsx

- 고양이 크기가 커지는 이슈가 있어서 패치 진행했습니다.
-

[HotFix] Bottom Image 고양이 크기 긴급 패치

---

src/app/personal/[id]/PhotoPreview.tsx
src/app/personal/[id]/page.tsx
src/component/OpenGraph.tsx

- 조회 페이지 바텀 버튼 영역 터치 영역에서 제거
- 조회 페이지 preview image left-1px, top-1px로 변경 absolute시
- twitter meta tag를 추가했습니다. (test를 못해서 나중에 다시 fix해야될수도 있을듯)

[Hotfix] bottom button & 조회 페이지 perview image변경

---

src/app/InApp.tsx

- insta에서 오류화면처럼 보여서, kakaotalk, line을 제외하고 모두 삭제했습니다.
-

hotfix : inapp browser kakaotalk, line제외 삭제

---

src/app/create/page.tsx
src/app/login/page.tsx
src/app/page.tsx
src/app/personal/[id]/add/page.tsx
src/app/personal/[id]/page.tsx
src/component/PhotoUpload.tsx
src/services/mixpanel.ts

- 로깅 이벤트 요소 추가
- 로깅 함수 추상화
- #335

[Feat] mixpanel#335

---

README.md

- 백엔드의 리드미를 복붙 및 몇가지 수정해서 업로드합니다. 
- 수정사항 
- 기술스택의 카테고리를 2개로 나누고, 프론트에 맞게 변경하고, 뱃지를 추가했습니다. 
- 팀원 및 역할에서 각자 맡은 부분을 명시했습니다. 혹시 추가로 원하는 문구가 있다면 코멘트로 요청해주세요
- #361

[Docs] : readme update

---

.github/ISSUE_TEMPLATE/design-report.md

- 디자인 작업 이슈 생성을 위한 디자인 이슈 템플릿 생성 & 라벨 생성

[Feat] design 템플릿 생성

---

src/app/personal/[id]/page.tsx

-  toast 호출 방식을 변경 하였습니다
- useToast로 만들어 전역 관리 로직으로 변경할까 했지만 사용하는 페이지가 personal 페이지 밖에 없어서 하지 않았습니다!
- #367

[Refactor] toast 호출 방식 변경#367
